# Generated by Django 4.2.7 on 2023-12-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_source_alter_rate_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Source', 'verbose_name_plural': 'Sources'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='buy',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Buy'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='change_type',
            field=models.SmallIntegerField(choices=[(1, 'Dollar_USA'), (2, 'Euro_Europe'), (3, 'Ukranian_hryvnia'), (4, 'Polish_zloty')], default=1, verbose_name='Change Type'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='sell',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sell'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.CharField(choices=[('PIVDENNY', 'Bank Pivdenny'), ('PRIVAT', 'Bank Privat'), ('CREADITDNEPR', 'Bank Credir Dnepro')], default='PRIVAT', max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(choices=[('PIVDENNY', 'Bank Pivdenny'), ('PRIVAT', 'Bank Privat'), ('CREADITDNEPR', 'Bank Credir Dnepro')], default='PRIVAT', max_length=64, verbose_name='Source name'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(choices=[('https://bank.com.ua/en', 'Bank Pivdenny'), ('https://en.privatbank.ua/', 'Bank Privat'), ('https://creditdnepr.com.ua/en', 'Bank Credir Dnepro')], max_length=255, verbose_name='Source url'),
        ),
    ]
