# Generated by Django 4.2.7 on 2023-12-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_contactus_options_alter_rate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='nikita', max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='change_type',
            field=models.SmallIntegerField(choices=[(1, 'Dollar_USA'), (2, 'Euro_Europe'), (3, 'Ukranian_hryvnia'), (4, 'Polish_zloty'), (5, 'Chinese_Yuan')], default=1, verbose_name='Change Type'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.CharField(choices=[('PIVDENNY', 'Bank Pivdenny'), ('PRIVAT', 'Bank Privat'), ('CREADITDNEPR', 'Bank Credir Dnepro'), ('MONOBANK', 'Bank Mono')], default='PRIVAT', max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(choices=[('PIVDENNY', 'Bank Pivdenny'), ('PRIVAT', 'Bank Privat'), ('CREADITDNEPR', 'Bank Credir Dnepro'), ('MONOBANK', 'Bank Mono')], default='PRIVAT', max_length=64, verbose_name='Source name'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(choices=[('https://bank.com.ua/en', 'Bank Pivdenny'), ('https://en.privatbank.ua/', 'Bank Privat'), ('https://creditdnepr.com.ua/en', 'Bank Credir Dnepro'), ('https://www.monobank.ua/?lang=en', 'Bank Mono')], max_length=255, verbose_name='Source url'),
        ),
    ]
