# Generated by Django 4.2.7 on 2023-12-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_contactus_name_alter_rate_change_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default='nikitaaa@gmail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=254, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='nikita', max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=254, verbose_name='Subject'),
        ),
    ]
