# Generated by Django 4.2.7 on 2023-12-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_alter_contactus_email_alter_contactus_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256, verbose_name='Path')),
                ('request_method', models.CharField(max_length=256, verbose_name='Request_method')),
                ('time', models.FloatField(verbose_name='Time')),
            ],
        ),
    ]
